import { useState, useEffect } from "react";
import { useStore } from "@/lib/storage";
import { fmt } from "@/lib/format";
import { supabase } from "@/lib/supabase"; 
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { AlertTriangle, UserCheck, LogIn, Clock, Printer, Wallet, ArrowRight } from "lucide-react";
import { useSession } from "@/App";
import { toast } from "sonner";
import { Link } from "@tanstack/react-router";

/* ── Shift Report Print ── */
function printShiftReport(report: {
  name: string;
  timeIn: string;
  timeOut: string;
  drawerStart: number;
  sales: number;
  txCount: number;
  currency: string;
}) {
  const fmt2 = (n: number) => `${report.currency}${n.toFixed(2)}`;
  const fmtTime = (iso: string) =>
    new Date(iso).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });

  const html = `<!doctype html><html><head><title>Shift Report</title>
    <style>
      body { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 13px; padding: 20px; max-width: 320px; margin: 0 auto; color: #000; background: #fff; }
      h2 { text-align: center; font-size: 16px; margin: 0 0 4px; }
      p.sub { text-align: center; color: #666; margin: 0 0 16px; font-size: 11px; }
      hr { border: none; border-top: 1px dashed #999; margin: 12px 0; }
      .row { display: flex; justify-content: space-between; margin: 4px 0; gap: 8px; }
      .label { color: #555; }
      .total { font-weight: bold; font-size: 15px; border-top: 1px solid #000; padding-top: 8px; margin-top: 8px; }
    </style></head><body>
    <h2>SHIFT REPORT</h2>
    <p class="sub">${new Date().toLocaleDateString([], { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</p>
    <hr/>
    <div class="row"><span class="label">Employee</span><span>${report.name}</span></div>
    <div class="row"><span class="label">Time In</span><span>${fmtTime(report.timeIn)}</span></div>
    <div class="row"><span class="label">Time Out</span><span>${report.timeOut ? fmtTime(report.timeOut) : "Active"}</span></div>
    <hr/>
    <div class="row"><span class="label">Drawer Start</span><span>${fmt2(report.drawerStart)}</span></div>
    <div class="row"><span class="label">Total Sales</span><span>${fmt2(report.sales)}</span></div>
    <div class="row"><span class="label">Transactions</span><span>${report.txCount}</span></div>
    <hr/>
    <div class="row total"><span>Total in Drawer</span><span>${fmt2(report.drawerStart + report.sales)}</span></div>
    <hr/>
    <p style="text-align:center;font-size:11px;color:#999;margin-top:16px;">Generated by YourStore</p>
    </body></html>`;

  // Use hidden iframe — popups are blocked in Android WebView & iOS Safari standalone
  let iframe = document.getElementById("shift-print-iframe") as HTMLIFrameElement | null;
  if (!iframe) {
    iframe = document.createElement("iframe");
    iframe.id = "shift-print-iframe";
    iframe.style.position = "fixed";
    iframe.style.right = "0";
    iframe.style.bottom = "0";
    iframe.style.width = "0";
    iframe.style.height = "0";
    iframe.style.border = "0";
    document.body.appendChild(iframe);
  }
  const doc = iframe.contentDocument;
  if (!doc) return;
  doc.open();
  doc.write(html);
  doc.close();
  setTimeout(() => {
    try { iframe!.contentWindow?.focus(); iframe!.contentWindow?.print(); } catch {}
  }, 300);
}

/* ── Owner Dashboard ── */
function OwnerDashboard() {
  const { transactions, products, utang, settings, shifts } = useStore();
  
  const [dbTransactions, setDbTransactions] = useState<any[]>([]);
  const [dbUtang, setDbUtang] = useState<any[]>([]);
  const [isHydrating, setIsHydrating] = useState<boolean>(true);

  useEffect(() => {
    const hydrateDashboardMetrics = async () => {
      try {
        const { data: session } = await supabase.auth.getUser();
        if (!session?.user) return;

        // 1. Fetch Transactions Safely
        const { data: txRows } = await supabase
          .from("transactions")
          .select("*")
          .eq("user_id", session.user.id);
        if (txRows) setDbTransactions(txRows);

        // 2. Fetch Utang and Payments separately to completely bypass the Schema Cache join bug
        const { data: utangRows } = await supabase
          .from("utang")
          .select("*")
          .eq("user_id", session.user.id);

        const { data: paymentRows } = await supabase
          .from("payments")
          .select("*")
          .eq("user_id", session.user.id);

        if (utangRows) {
          // Manually combine rows together in application memory
          const stitchedUtang = utangRows.map((u) => ({
            ...u,
            payments: paymentRows ? paymentRows.filter((p: any) => p.utang_id === u.id) : []
          }));
          setDbUtang(stitchedUtang);
        }

      } catch (err) {
        console.error("Dashboard hydration error:", err);
      } finally {
        setIsHydrating(false);
      }
    };

    hydrateDashboardMetrics();
  }, []);

  const activeTransactions = dbTransactions.length > 0 ? dbTransactions : transactions;
  const activeUtang = dbUtang.length > 0 ? dbUtang : utang;

  // Standardized Date Matching Engine (Bypasses helper formatting issues)
  const todayISO = new Date().toISOString().split("T")[0];
  const today = activeTransactions.filter((t) => {
    if (t.voided) return false;
    try {
      const txDateString = new Date(t.date).toISOString().split("T")[0];
      return txDateString === todayISO;
    } catch {
      return false;
    }
  });

  const totalSales = today.reduce((s, t) => s + t.total, 0);
  const txCount = today.length;

  const counts = new Map<string, number>();
  today.forEach((t) => t.items?.forEach((i: any) => counts.set(i.name, (counts.get(i.name) ?? 0) + i.qty)));
  const top = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5);

  const lowStock = products.filter((p) => p.stock <= settings.lowStockThreshold);
  
  const totalUtang = activeUtang.reduce((s, u) => {
    const paid = u.payments?.reduce((a: number, p: any) => a + p.amount, 0) ?? 0;
    return s + (u.amount - paid);
  }, 0);

  // Filter shifts matching active ISO day
  const todayShifts = shifts.filter((s) => {
    try {
      return new Date(s.timeIn).toISOString().split("T")[0] === todayISO && s.timeOut;
    } catch {
      return false;
    }
  });

  return (
    <div className="space-y-4 p-4">
      {/* Stats */}
      <div className="grid grid-cols-2 gap-3">
        <Card className="glass-card">
          <CardHeader className="pb-1 pt-3 px-3">
            <CardTitle className="text-[11px] text-muted-foreground uppercase tracking-wider">Today's Sales</CardTitle>
          </CardHeader>
          <CardContent className="px-3 pb-3 text-2xl font-bold text-primary">
            {isHydrating && dbTransactions.length === 0 ? (
              <span className="text-xs text-slate-500 animate-pulse">Loading...</span>
            ) : (
              fmt(totalSales, settings.currency)
            )}
          </CardContent>
        </Card>
        <Card className="glass-card">
          <CardHeader className="pb-1 pt-3 px-3">
            <CardTitle className="text-[11px] text-muted-foreground uppercase tracking-wider">Transactions</CardTitle>
          </CardHeader>
          <CardContent className="px-3 pb-3 text-2xl font-bold">
            {isHydrating && dbTransactions.length === 0 ? (
              <span className="text-xs text-slate-500 animate-pulse">—</span>
            ) : (
              txCount
            )}
          </CardContent>
        </Card>
        <Card className="glass-card col-span-2">
          <CardHeader className="pb-1 pt-3 px-3">
            <CardTitle className="text-[11px] text-muted-foreground uppercase tracking-wider">Outstanding Utang</CardTitle>
          </CardHeader>
          <CardContent className="px-3 pb-3 text-2xl font-bold text-amber-400">
            {isHydrating && dbUtang.length === 0 ? (
              <span className="text-xs text-slate-500 animate-pulse">Syncing...</span>
            ) : (
              fmt(totalUtang, settings.currency)
            )}
          </CardContent>
        </Card>
      </div>

      {/* Cash Drawer Audit Link */}
      <Link to="/drawer" className="block transition-all active:scale-[0.99]">
        <Card className="glass-card border-amber-500/10 hover:border-amber-500/30 transition-colors">
          <CardContent className="p-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-amber-500/10 rounded-xl border border-amber-500/20 text-amber-400">
                <Wallet className="h-5 w-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-white tracking-wide">Cash Drawer Audit</h3>
                <p className="text-[11px] text-muted-foreground mt-0.5">
                  Analyze current real-time register cash flow & log manual changes.
                </p>
              </div>
            </div>
            <ArrowRight className="h-4 w-4 text-muted-foreground" />
          </CardContent>
        </Card>
      </Link>

      {/* Top sellers */}
      <Card className="glass-card">
        <CardHeader className="px-4 pt-4 pb-2">
          <CardTitle className="text-sm font-semibold">Top Sellers Today</CardTitle>
        </CardHeader>
        <CardContent className="px-4 pb-4 space-y-2">
          {top.length === 0 && <p className="text-sm text-muted-foreground">No sales yet today.</p>}
          {top.map(([name, qty]) => (
            <div key={name} className="flex justify-between text-sm">
              <span className="truncate max-w-[180px]">{name}</span>
              <Badge variant="secondary">{qty}</Badge>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Low stock */}
      {lowStock.length > 0 && (
        <Card className="glass-card border-amber-500/20">
          <CardHeader className="px-4 pt-4 pb-2">
            <CardTitle className="text-sm font-semibold flex items-center gap-1.5">
              <AlertTriangle className="h-4 w-4 text-amber-400" />
              Low Stock
            </CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4 space-y-2">
            {lowStock.map((p) => (
              <div key={p.id} className="flex justify-between text-sm">
                <span>{p.name}</span>
                <Badge variant="destructive">{p.stock}</Badge>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      {/* Shift reports */}
      {todayShifts.length > 0 && (
        <Card className="glass-card">
          <CardHeader className="px-4 pt-4 pb-2">
            <CardTitle className="text-sm font-semibold">Today's Shift Reports</CardTitle>
          </CardHeader>
          <CardContent className="px-4 pb-4 space-y-3">
            {todayShifts.map((shift) => {
              const drawerStart = (shift as any).drawerStart ?? 0;
              const totalDrawer = drawerStart + shift.totalSales;
              return (
                <div key={shift.id} className="rounded-xl border border-white/8 p-3 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-medium text-sm">{shift.employeeName}</span>
                    <Button
                      size="sm"
                      variant="ghost"
                      className="h-7 px-2 text-xs"
                      onClick={() => printShiftReport({
                        name: shift.employeeName,
                        timeIn: shift.timeIn,
                        timeOut: shift.timeOut ?? "",
                        drawerStart,
                        sales: shift.totalSales,
                        txCount: shift.txCount,
                        currency: settings.currency,
                      })}
                    >
                      <Printer className="h-3.5 w-3.5 mr-1" />Print
                    </Button>
                  </div>
                  <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-xs text-muted-foreground">
                    <div>Time In: <span className="text-foreground">{new Date(shift.timeIn).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span></div>
                    <div>Time Out: <span className="text-foreground">{shift.timeOut ? new Date(shift.timeOut).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</span></div>
                    <div>Drawer Start: <span className="text-foreground">{fmt(drawerStart, settings.currency)}</span></div>
                    <div>Sales: <span className="text-emerald-400 font-medium">{fmt(shift.totalSales, settings.currency)}</span></div>
                    <div className="col-span-2 pt-1 border-t border-white/8">
                      Total in Drawer: <span className="text-primary font-bold">{fmt(totalDrawer, settings.currency)}</span>
                    </div>
                  </div>
                </div>
              );
            })}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

/* ── Employee Dashboard ── */
function EmployeeDashboard() {
  const { activeShift, startShift, endShift, settings } = useStore();
  const [showDialog, setShowDialog] = useState(false);
  const [empName, setEmpName] = useState("");
  const [drawerAmount, setDrawerAmount] = useState("");
  const [endConfirm, setEndConfirm] = useState(false);

  const fmt2 = (n: number) => fmt(n, settings.currency);

  const handleStart = () => {
    if (!empName.trim()) { toast.error("Enter your name"); return; }
    startShift(empName.trim(), Number(drawerAmount) || 0);
    setShowDialog(false);
    setEmpName("");
    setDrawerAmount("");
    toast.success(`Shift started — welcome, ${empName.trim()}!`);
  };

  const handleEnd = () => {
    endShift();
    setEndConfirm(false);
    toast.success("Shift ended. Have a good rest!");
  };

  if (!activeShift) {
    return (
      <div className="flex min-h-[70vh] flex-col items-center justify-center gap-4 p-6 text-center">
        <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-muted/30 ring-1 ring-white/10">
          <Clock className="h-8 w-8 text-muted-foreground" />
        </div>
        <div>
          <p className="text-lg font-bold">You're not clocked in</p>
          <p className="text-sm text-muted-foreground mt-1">Start a shift to track your sales and time.</p>
        </div>
        <Button className="w-full max-w-xs rounded-xl" onClick={() => { setEmpName(""); setDrawerAmount(""); setShowDialog(true); }}>
          <LogIn className="h-4 w-4 mr-2" />Clock In
        </Button>

        <Dialog open={showDialog} onOpenChange={setShowDialog}>
          <DialogContent className="max-w-xs glass-card">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <LogIn className="h-5 w-5 text-primary" />Start Your Shift
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-3">
              <div className="space-y-1">
                <Label className="text-xs">Your Name</Label>
                <Input placeholder="e.g. Maria" value={empName}
                  onChange={(e) => setEmpName(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleStart()} autoFocus />
              </div>
              <div className="space-y-1">
                <Label className="text-xs">Starting Cash in Drawer ({settings.currency})</Label>
                <Input type="number" min={0} placeholder="0.00"
                  value={drawerAmount} onChange={(e) => setDrawerAmount(e.target.value)} />
                <p className="text-[11px] text-muted-foreground">Count the cash before you start.</p>
              </div>
            </div>
            <DialogFooter>
              <Button className="w-full rounded-xl" onClick={handleStart}>Clock In</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  const timeIn = new Date(activeShift.timeIn);
  const elapsed = Math.floor((Date.now() - timeIn.getTime()) / 60000);
  const hours = Math.floor(elapsed / 60);
  const mins = elapsed % 60;
  const duration = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
  const drawerStart = (activeShift as any).drawerStart ?? 0;
  const totalDrawer = drawerStart + activeShift.totalSales;
  const topItems = [...activeShift.items].sort((a, b) => b.total - a.total);

  return (
    <div className="space-y-4 p-4">
      <Card className="glass-card border-primary/20">
        <CardContent className="pt-4 pb-3 px-4 space-y-3">
          <div className="flex items-start justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Employee</p>
              <p className="text-xl font-bold">{activeShift.employeeName}</p>
            </div>
            <Badge variant="outline" className="text-emerald-400 border-emerald-500/40 bg-emerald-500/10">
              On Shift
            </Badge>
          </div>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div className="rounded-lg bg-white/5 px-3 py-2">
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Time In</p>
              <p className="font-medium">{timeIn.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p>
            </div>
            <div className="rounded-lg bg-white/5 px-3 py-2">
              <p className="text-[10px] text-muted-foreground uppercase tracking-wider">Duration</p>
              <p className="font-medium">{duration}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="glass-card">
        <CardHeader className="px-4 pt-4 pb-2">
          <CardTitle className="text-sm font-semibold">Cash Drawer</CardTitle>
        </CardHeader>
        <CardContent className="px-4 pb-4 space-y-2">
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Drawer Start</span>
            <span>{fmt2(drawerStart)}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-muted-foreground">Sales This Shift</span>
            <span className="text-emerald-400 font-medium">{fmt2(activeShift.totalSales)}</span>
          </div>
          <div className="flex justify-between text-sm font-bold border-t border-white/10 pt-2">
            <span>Total in Drawer</span>
            <span className="text-primary">{fmt2(totalDrawer)}</span>
          </div>
          <div className="flex justify-between text-xs text-muted-foreground pt-1">
            <span>Transactions</span>
            <span>{activeShift.txCount}</span>
          </div>
        </CardContent>
      </Card>

      <Card className="glass-card">
        <CardHeader className="px-4 pt-4 pb-2">
          <CardTitle className="text-sm font-semibold">Items Sold This Shift</CardTitle>
        </CardHeader>
        <CardContent className="px-4 pb-4 space-y-2">
          {topItems.length === 0 && <p className="text-sm text-muted-foreground">No sales yet — start scanning!</p>}
          {topItems.map((item) => (
            <div key={item.productId} className="flex items-center justify-between text-sm">
              <div className="flex items-center gap-2">
                <Badge variant="secondary" className="min-w-[2rem] justify-center">{item.qty}</Badge>
                <span className="truncate max-w-[160px]">{item.name}</span>
              </div>
              <span className="font-medium shrink-0">{fmt2(item.total)}</span>
            </div>
          ))}
        </CardContent>
      </Card>

      <Button variant="destructive" className="w-full rounded-xl" onClick={() => setEndConfirm(true)}>
        Clock Out
      </Button>

      <Dialog open={endConfirm} onOpenChange={setEndConfirm}>
        <DialogContent className="max-w-xs glass-card">
          <DialogHeader><DialogTitle>End Shift?</DialogTitle></DialogHeader>
          <div className="space-y-2 text-sm text-muted-foreground">
            <p>Shift summary for <strong className="text-foreground">{activeShift.employeeName}</strong>:</p>
            <div className="rounded-xl bg-white/5 p-3 space-y-1.5">
              <div className="flex justify-between"><span>Duration</span><span className="text-foreground font-medium">{duration}</span></div>
              <div className="flex justify-between"><span>Drawer Start</span><span className="text-foreground font-medium">{fmt2(drawerStart)}</span></div>
              <div className="flex justify-between"><span>Total Sales</span><span className="text-emerald-400 font-medium">{fmt2(activeShift.totalSales)}</span></div>
              <div className="flex justify-between border-t border-white/10 pt-1.5"><span>Total in Drawer</span><span className="text-primary font-bold">{fmt2(totalDrawer)}</span></div>
            </div>
            <p className="text-xs">This will record your time-out.</p>
          </div>
          <DialogFooter className="gap-2 flex-col sm:flex-col">
            <Button variant="destructive" className="w-full" onClick={handleEnd}>Yes, Clock Out</Button>
            <Button variant="outline" className="w-full" onClick={() => setEndConfirm(false)}>Keep Working</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export function Dashboard() {
  const role = useSession((s) => s.role);
  return role === "owner" ? <OwnerDashboard /> : <EmployeeDashboard />;
}
